#!/bin/bash
# Generate Status Script
# Updates CURRENT_STATUS.md with latest project state

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

STATUS_FILE="sessions/CURRENT_STATUS.md"
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")

echo "Generating current status..."

# Read current phase from config
PHASE="unknown"
if [ -f "config/project.yml" ]; then
    PHASE=$(grep "phase:" config/project.yml | awk '{print $2}' | tr -d '"' || echo "unknown")
fi

# Get current branch
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Get recent commits
RECENT_COMMITS=$(git log --oneline -5 2>/dev/null || echo "No commits yet")

# Count decisions
DECISION_COUNT=$(find decisions -name "*.md" -type f 2>/dev/null | grep -v README | wc -l || echo "0")

# Check for recent session logs
LATEST_SESSION=$(ls -t sessions/session-*.md 2>/dev/null | head -1 || echo "")

cat > "$STATUS_FILE" << EOF
# Current Project Status

**Last Updated:** $TIMESTAMP
**Phase:** $PHASE
**Branch:** $BRANCH

## Quick Context

Project Perplex is bridging local AI development tools with Perplexity AI's research capabilities.

## Current State

### Git Status
\`\`\`
$(git status --short 2>/dev/null || echo "Unable to get git status")
\`\`\`

### Recent Commits
\`\`\`
$RECENT_COMMITS
\`\`\`

### Statistics
- Decisions Logged: $DECISION_COUNT
- Latest Session: $(basename "$LATEST_SESSION" 2>/dev/null || echo "None")

## Recent Decisions

$(if [ $DECISION_COUNT -gt 0 ]; then
    echo "Last 3 decisions:"
    ls -t decisions/*.md 2>/dev/null | grep -v README | head -3 | while read decision; do
        echo "- $(basename "$decision")"
    done
else
    echo "(No decisions logged yet)"
fi)

## For Next Session

1. Read \`/FOUNDATION.md\` first
2. Review this file for context
3. Check recent decisions in \`/decisions\`
4. Review \`/docs/PRODUCT_VISION.md\` for alignment
5. Check latest session log: \`$LATEST_SESSION\`

## Notes

This file is automatically generated. For detailed session information,
see individual session logs in \`/sessions/\`.

---

**Update Protocol:**
Run \`tools/generate-status.sh\` to regenerate this file.
EOF

echo "✓ Status updated: $STATUS_FILE"
